name: Deploy workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Install dependencies
      run: npm install

    - name: Run the application
      run: sudo node index.js
