
name: Deploy workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run the application in the 'projet2' directory
      run: |
        cd ..
        cd ..
        cd ..
        cd projet2/
        sudo node index.js
